"""change utc_created column type to DateTime

Revision ID: 0e9b03a76fb0
Revises: a754542c61b9
Create Date: 2021-06-14 02:30:11.687819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '0e9b03a76fb0'
down_revision = 'a754542c61b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Posts', 'created_utc',
               existing_type=mssql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Posts', 'created_utc',
               existing_type=sa.DateTime(),
               type_=mssql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
