"""change created_utc to type DateTime

Revision ID: 4e5e0ebc036e
Revises: a754542c61b9
Create Date: 2021-06-14 02:21:31.781280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5e0ebc036e'
down_revision = 'a754542c61b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
