"""add columns defining reddit post

Revision ID: a754542c61b9
Revises: 007ee1305668
Create Date: 2021-06-14 00:00:51.823213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a754542c61b9'
down_revision = '007ee1305668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('created_utc', sa.Time(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('upvote_ratio', sa.Float(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('num_crossposts', sa.Integer(), nullable=True),
    sa.Column('total_awards_received', sa.Integer(), nullable=True),
    sa.Column('subreddit_name', sa.String(), nullable=True),
    sa.Column('subreddit_id', sa.String(), nullable=True),
    sa.Column('subreddit_subscribers', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('gilded', sa.Integer(), nullable=True),
    sa.Column('gilded_silver', sa.Integer(), nullable=True),
    sa.Column('gilded_gold', sa.Integer(), nullable=True),
    sa.Column('gilded_platinum', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('is_meta', sa.Boolean(), nullable=True),
    sa.Column('is_nsfw', sa.Boolean(), nullable=True),
    sa.Column('is_oc', sa.Boolean(), nullable=True),
    sa.Column('is_self', sa.Boolean(), nullable=True),
    sa.Column('is_spoiler', sa.Boolean(), nullable=True),
    sa.Column('is_video', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Posts')
    # ### end Alembic commands ###
